/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A builder for constructing SedonaDB session contexts with custom
 * runtime configuration (memory limits, spill directories, pool type).
 *
 * The builder defaults to an interactive context (local filesystem access,
 * all spatial functions registered). Use `.localInteractive(false)` for
 * a lightweight in-memory-only context.
 */
export declare class ContextBuilder {
  /** Create a new builder with default settings. */
  constructor()
  /**
   * Set the memory limit as a human-readable string (e.g. "4gb", "512m", "1.5g")
   * or a plain byte count. Pass "unlimited" to use the default (75% of RAM).
   */
  memoryLimit(limit: string): ContextBuilder
  /** Use the default memory limit (75% of total physical memory). */
  withoutMemoryLimit(): ContextBuilder
  /** Set the directory for temporary/spill files. */
  tempDir(dir: string): ContextBuilder
  /** Set the memory pool type: "fair" or "greedy". */
  poolType(poolType: string): ContextBuilder
  /** Set the fraction of memory reserved for unspillable consumers (0.0 to 1.0). */
  unspillableReserveRatio(ratio: number): ContextBuilder
  /** Set whether to create an interactive context with local filesystem access. */
  localInteractive(interactive: boolean): ContextBuilder
  /** Build the session context from the current configuration. */
  build(): Promise<SessionContext>
}

/**
 * A SedonaDB DataFrame — wraps a DataFusion DataFrame with spatial extensions.
 *
 * Returned from `SessionContext.sql()` and `readParquet()`.
 * Supports chaining operations like `.sortBy()`, `.select()`, `.limit()`.
 */
export declare class SedonaDataFrame {
  /** Get the schema of this DataFrame */
  schema(): Array<SchemaField>
  /**
   * Execute the DataFrame and return all rows as arrays of strings.
   *
   * Each value is formatted using Arrow's Display implementation.
   * Null values are returned as empty strings.
   */
  collect(): Promise<Array<Array<string>>>
  /**
   * Print the first `limit` rows as a formatted ASCII table string.
   *
   * If `limit` is not provided, all rows are shown.
   */
  showSedona(limit?: number | undefined | null): Promise<string>
  /**
   * Sort the DataFrame by the specified columns.
   *
   * Each column can optionally be followed by " DESC" for descending order.
   * Example: `df.sortBy(["name", "population DESC"])`
   */
  sortBy(cols: Array<string>): Promise<SedonaDataFrame>
  /** Select specific columns from the DataFrame. */
  select(cols: Array<string>): Promise<SedonaDataFrame>
  /** Limit the number of rows in the DataFrame. */
  limit(n: number): Promise<SedonaDataFrame>
}

export declare class SessionContext {
  /**
   * Create a new interactive session with default settings.
   *
   * Equivalent to `new ContextBuilder().build()` — uses 75% of physical
   * memory, fair pool, local filesystem access, and all spatial functions.
   */
  static new(): Promise<SessionContext>
  /**
   * Create a new local interactive session with default spatial functions
   * and local filesystem access.
   *
   * This is equivalent to `SessionContext.new()`.
   */
  static newLocalInteractive(): Promise<SessionContext>
  /** Execute a SQL query and return the results as a structured object. */
  sql(query: string): Promise<QueryResult>
  /** Register a DataFrame as a temporary view for SQL queries. */
  registerTable(name: string, df: SedonaDataFrame): void
  /** Read a GeoParquet file and return a DataFrame for further processing. */
  readParquet(path: string): Promise<SedonaDataFrame>
}

/**
 * A SedonaDB session context — the entry point for all spatial data operations.
 *
 * Wraps SedonaContext (which itself extends DataFusion's SessionContext) with
 * all spatial functions, GeoParquet support, and object store configuration.
 */
export interface QueryResult {
  /** Column names in result order */
  columns: Array<string>
  /** Row-oriented data — each inner vec is one row's values as strings */
  rows: Array<Array<string>>
  /** Number of rows returned */
  numRows: number
}

/** Schema field metadata */
export interface SchemaField {
  /** Column name */
  name: string
  /** Arrow data type name (e.g. "Utf8", "Float64", "Int32") */
  dataType: string
  /** Whether the column is nullable */
  nullable: boolean
}
